# Generated by Django 4.1.6 on 2023-02-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('Sweatshirt', 'Sweatshirt'), ('Hoody', 'Hoody'), ('Gown', 'Gown')], max_length=100)),
                ('image', models.ImageField(upload_to='product_images')),
                ('price', models.FloatField()),
                ('discount_price', models.TextField()),
            ],
        ),
    ]
